/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sdt_testthreeso_FunCaller */

#ifndef _Included_com_sdt_testthreeso_FunCaller
#define _Included_com_sdt_testthreeso_FunCaller


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sdt_testthreeso_FunCaller
 * Method:    autoIncreasing
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sdt_testthreeso_FunCaller_autoIncreasing
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sdt_testthreeso_FunCaller
 * Method:    encryptString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sdt_testthreeso_FunCaller_encryptString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_sdt_testthreeso_FunCaller
 * Method:    encryptBytes
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sdt_testthreeso_FunCaller_encryptBytes
  (JNIEnv *, jclass, jbyteArray, jint length);

/*
 * Class:     com_sdt_testthreeso_FunCaller
 * Method:    encryptChars
 * Signature: ([C)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_sdt_testthreeso_FunCaller_encryptChars
  (JNIEnv *, jclass, jcharArray, jint length);

/*
 * Class:     com_sdt_testthreeso_FunCaller
 * Method:    calcBit
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_com_sdt_testthreeso_FunCaller_calcBit
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_sdt_testthreeso_FunCaller
 * Method:    calcMumber
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_sdt_testthreeso_FunCaller_calcMumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sdt_testthreeso_FunCaller
 * Method:    calcHeight
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_sdt_testthreeso_FunCaller_calcHeight
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_sdt_testthreeso_FunCaller
 * Method:    calcDistance
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_sdt_testthreeso_FunCaller_calcDistance
  (JNIEnv *, jclass, jdouble);


/*
 * Class:     com_sdt_testthreeso_FunCaller
 * Method:    writeFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sdt_testthreeso_FunCaller_writeFile
        (JNIEnv *, jclass, jstring, jstring text);


#ifdef __cplusplus
}
#endif
#endif
